//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrozzeria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrozzeria()
        {
            this.CommesseXCarrozzerie = new HashSet<CommesseXCarrozzerie>();
            this.TelaiAnagrafica = new HashSet<TelaiAnagrafica>();
            this.TelaiAnagrafica1 = new HashSet<TelaiAnagrafica>();
            this.TelaiAnagrafica2 = new HashSet<TelaiAnagrafica>();
        }
    
        public int ID { get; set; }
        public string RagioneSociale { get; set; }
        public string Mail { get; set; }
        public string Tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommesseXCarrozzerie> CommesseXCarrozzerie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelaiAnagrafica> TelaiAnagrafica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelaiAnagrafica> TelaiAnagrafica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelaiAnagrafica> TelaiAnagrafica2 { get; set; }
    }
}
