//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoXTelaio
    {
        public int ID { get; set; }
        public Nullable<int> IDTelaio { get; set; }
        public Nullable<int> IDTipoDocumento { get; set; }
        public string NomeFile { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string InsertUsert { get; set; }
    
        public virtual TelaiAnagrafica TelaiAnagrafica { get; set; }
        public virtual TipiDocumento TipiDocumento { get; set; }
    }
}
