//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ricambi
    {
        public int ID { get; set; }
        public int IDTelaio { get; set; }
        public bool COFANO_ANT { get; set; }
        public bool LOGO_ANT { get; set; }
        public bool FANALE_ANT_SX { get; set; }
        public bool FRECCIA_PARAURT_ANT_SX { get; set; }
        public bool CATADIOTTRO_ANT_SX { get; set; }
        public bool FRECCIA_PARAFANGO_ANT_SX { get; set; }
        public bool CALANDRA_SOTTOPARABREZZA { get; set; }
        public bool PARABREZZA { get; set; }
        public bool GUARNIZIONE_PARABREZZA_SX { get; set; }
        public bool CORPO_SPECCHIO_SX { get; set; }
        public bool VETRINO_SPECCHIO_RETROVISORE_SX { get; set; }
        public bool CALOTTA_SX { get; set; }
        public bool FRECCIA_SPECCHIO_SX { get; set; }
        public bool CORNICE_PORTA_ANT_SX { get; set; }
        public bool MONTANTE_ANT_PORTA_ANT_SX { get; set; }
        public bool MONTANTE_POST_PORTA_ANT_SX { get; set; }
        public bool CORNICE_PORTA_POST_SX { get; set; }
        public bool MONTANTE_ANT_PORTA_POST_SX { get; set; }
        public bool MONTANTE_POST_PORTA_POST_SX { get; set; }
        public bool CORNICE_PARAFANGO_SX { get; set; }
        public bool RASAVETRO_ANT_SX { get; set; }
        public bool RASAVETRO_POST_SX { get; set; }
        public bool CORRIMANO_SX { get; set; }
        public bool BASE_ANTENNA { get; set; }
        public bool TERZO_STOP { get; set; }
        public bool CORNICE_COFANO_POST { get; set; }
        public bool FANALE_POST_PARAFANGO_SX { get; set; }
        public bool COFANO_POST { get; set; }
        public bool LOGO_POST { get; set; }
        public bool LUNOTTO { get; set; }
        public bool CAPPELLIERA { get; set; }
        public bool SPORTELLO_CARBURANTE { get; set; }
        public bool CORRIMANO_DX { get; set; }
        public bool RASAVETRO_POST_DX { get; set; }
        public bool RASAVETRO_ANT_DX { get; set; }
        public bool CORNICE_PARAFANGO_DX { get; set; }
        public bool CORNICE_PORTA_POST_DX { get; set; }
        public bool MONTANTE_ANT_PORTA_POST_DX { get; set; }
        public bool MONTANTE_POST_PORTA_POST_DX { get; set; }
        public bool CORNICE_PORTA_ANT_DX { get; set; }
        public bool MONTANTE_ANT_PORTA_ANT_DX { get; set; }
        public bool MONTANTE_POST_PORTA_ANT_DX { get; set; }
        public bool CORPO_SPECCHIO_DX { get; set; }
        public bool VETRINO_SPECCHIO_RETROVISORE_DX { get; set; }
        public bool CALOTTA_DX { get; set; }
        public bool FRECCIA_SPECCHIO_DX { get; set; }
        public bool GUARNIZIONE_PARABREZZA_DX { get; set; }
        public bool FRECCIA_PARAFANGO_ANT_DX { get; set; }
        public bool CATADIOTTRO_ANT_DX { get; set; }
        public bool FANALE_ANT_DX { get; set; }
        public bool FRECCIA_PARAURTI_ANT_DX { get; set; }
    
        public virtual TelaiAnagrafica TelaiAnagrafica { get; set; }
    }
}
