//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelaiAnagraficaFlat_vw
    {
        public int ID { get; set; }
        public string Telaio { get; set; }
        public string Modello { get; set; }
        public string Targa { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string NomeFile { get; set; }
        public Nullable<int> IDCommessa { get; set; }
        public string Commessa { get; set; }
        public string Annotazioni { get; set; }
        public Nullable<System.DateTime> DataIn { get; set; }
        public Nullable<System.DateTime> DataOut { get; set; }
        public string NFattAttiva { get; set; }
        public Nullable<System.DateTime> DataFattAtt { get; set; }
        public Nullable<double> ImpFattAtt { get; set; }
        public string Tecnico { get; set; }
        public string NumFattTecnico { get; set; }
        public Nullable<System.DateTime> DataFatturaPassiva { get; set; }
        public Nullable<double> ImportoFattPass { get; set; }
        public string Carrozzeria_1 { get; set; }
        public string NumFattCarrozzeria1 { get; set; }
        public Nullable<System.DateTime> DataFatturaCarrozzeria1 { get; set; }
        public Nullable<double> ImportoCarrozzeria1 { get; set; }
        public Nullable<int> IDCarrozzeria2 { get; set; }
        public string Carrozzera_2 { get; set; }
        public string NumFattCarrozzeria2 { get; set; }
        public Nullable<System.DateTime> DataFatturaCarrozzeria2 { get; set; }
        public Nullable<double> ImportoCarrozzeria2 { get; set; }
        public Nullable<int> IDCarrozzeria3 { get; set; }
        public string Carrozzeria_3 { get; set; }
        public string NumFattCarrozzeria3 { get; set; }
        public Nullable<System.DateTime> DataFatturaCarrozzeria3 { get; set; }
        public Nullable<double> ImportoCarrozzeria3 { get; set; }
        public Nullable<int> IDCarglass { get; set; }
        public string CarGlass { get; set; }
        public string NumFattCarGlass { get; set; }
        public Nullable<double> ImportoFattCarGlass { get; set; }
        public Nullable<System.DateTime> DataFatturaCarglass { get; set; }
        public Nullable<int> IDBisarchistaAndata { get; set; }
        public string BisarchistaAndata { get; set; }
        public string NumFattBisarchistaA { get; set; }
        public Nullable<System.DateTime> DataFattBisarchistaA { get; set; }
        public Nullable<double> CostoAndata { get; set; }
        public Nullable<int> IDBisarchistaRitorno { get; set; }
        public string BisarchistaRitorno { get; set; }
        public string NumFattBisarchistaR { get; set; }
        public Nullable<System.DateTime> DataFattBisarchistaR { get; set; }
        public Nullable<double> CostoRitorno { get; set; }
        public Nullable<double> Costi { get; set; }
        public string Chiave { get; set; }
        public string Fila { get; set; }
        public Nullable<int> IDGravita { get; set; }
        public string Gravita { get; set; }
        public bool IsUrgente { get; set; }
        public bool VerificatoNSG { get; set; }
        public bool VerificatoCliente { get; set; }
        public string LastStatus { get; set; }
    }
}
