//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telai_LastStatus_vw
    {
        public int ID { get; set; }
        public string Telaio { get; set; }
        public string Modello { get; set; }
        public string LastStatus { get; set; }
    }
}
