//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grandine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti
    {
        public string ID { get; set; }
        public string Nome { get; set; }
        public string Password { get; set; }
        public int IDClasse { get; set; }
        public string Cognome { get; set; }
    
        public virtual ClassiUtente ClassiUtente { get; set; }
    }
}
